### ISSUE TITLE
1 - Lox Language

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox-student#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Tests

- [x] The interpreter program executes successfully (mvn exec:java)

- [ ] Test cases pass; program prints the fish (mvn test)
- The command returned the error code 1 

## Lox Programming

- [ ] Program contains at least 3 Lox language comments
- Found 1 comment(s) in the test.lox or the output 

## TODOs

- [ ] Program file contains no TODOs
- Found 1 fragment(s) in the test.lox or the output while expecting exactly 0 
- [ ] Reflection contains no TODOs
- Found 5 fragment(s) in the reflection.md or the output while expecting exactly 0 

## Reflection

- [ ] Reflection responds to all open-ended, free-response prompts
- Found 2 paragraph(s) in the reflection.md file 
- [ ] Reflection contains adequate number of code fences
- Found 1 tag(s) in the reflection.md file 

## Percent complete

Based on the checks achieved, this assignment is `14%` complete.
