### ISSUE TITLE
2 - Scanning

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox-student#2]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Tests

- [x] The interpreter program executes successfully (mvn exec:java)

- [x] Test cases pass; program handles multi-line comments without breaking other functionality (mvn test)

## Lox Programming

- [ ] Program contains at least 1 Lox multi-line comment
- Found 0 comment(s) in the test.lox or the output 

## TODOs

- [x] Program file contains no TODOs

- [ ] Reflection contains no TODOs
- Found 6 fragment(s) in the reflection.md or the output while expecting exactly 0 

## Reflection

- [ ] Reflection responds to all open-ended, free-response prompts
- Found 2 paragraph(s) in the reflection.md file 
- [x] Reflection contains adequate number of code fences

## Percent complete

Based on the checks achieved, this assignment is `57%` complete.
