### ISSUE TITLE
4 - Parsing Expressions

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox-student#3]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Tests

- [ ] The interpreter program executes successfully (mvn exec:java)
- The command returned the error code 65 
- [ ] Comma expression production rule functions correctly
- The command returned the error code 1 
- [ ] Ternary expression production rule functions correctly
- The command returned the error code 1 

## TODOs

- [ ] Parser.java contains no TODOs
- Found 2 fragment(s) in the Parser.java or the output while expecting exactly 0 
- [ ] TokenType.java contains no TODOs
- Found 1 fragment(s) in the TokenType.java or the output while expecting exactly 0 
- [ ] ASTPrinter.java contains no TODOs
- Found 1 fragment(s) in the ASTPrinter.java or the output while expecting exactly 0 
- [ ] Scanner.java contains no TODOs
- Found 1 fragment(s) in the Scanner.java or the output while expecting exactly 0 
- [ ] Reflection contains no TODOs
- Found 3 fragment(s) in the reflection.md or the output while expecting exactly 0 

## Percent complete

Based on the checks achieved, this assignment is `0%` complete.
