### ISSUE TITLE
5 - Evaluating Expressions

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox-student#4]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Tests

- [ ] Divide by zero throws a RuntimeError
- The command returned the error code 1 
- [ ] String concatenation works correctly
- The command returned the error code 1 
- [ ] String multiplication works correctly
- The command returned the error code 1 

## TODOs

- [ ] Interpreter.java contains no TODOs
- Found 3 fragment(s) in the Interpreter.java or the output while expecting exactly 0 
- [ ] Reflection contains no TODOs
- Found 4 fragment(s) in the reflection.md or the output while expecting exactly 0 

## Percent complete

Based on the checks achieved, this assignment is `0%` complete.
