### ISSUE TITLE
6 - Statements and State

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox-student#5]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Tests

- [ ] Programs require variable initialization before use in a program
- The command returned the error code 1 
- [ ] The Lox interpreter&#39;s REPL mode works correctly; evaluates expressions and statements
- The command returned the error code 1 

## TODOs

- [ ] Interpreter.java contains no TODOs
- Found 1 fragment(s) in the Interpreter.java or the output while expecting exactly 0 
- [ ] Parser.java contains no TODOs
- Found 2 fragment(s) in the Parser.java or the output while expecting exactly 0 
- [ ] Main.java contains no TODOs
- Found 1 fragment(s) in the Main.java or the output while expecting exactly 0 
- [ ] Reflection contains no TODOs
- Found 4 fragment(s) in the reflection.md or the output while expecting exactly 0 

## Percent complete

Based on the checks achieved, this assignment is `0%` complete.
