### ISSUE TITLE
3 - Representing Code

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox-student#6]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Tests

- [ ] The interpreter program executes successfully (mvn exec:java)
- The command returned the error code 1 
- [ ] Test cases pass; both AST and RPN representations are correct
- The command returned the error code 1 

## TODOs

- [ ] test.lox program contains no TODOs
- Found 1 fragment(s) in the test.lox or the output while expecting exactly 0 
- [ ] Reflection contains no TODOs
- Found 2 fragment(s) in the reflection.md or the output while expecting exactly 0 
- [ ] ASTPrinter.java contains no TODOs
- Found 3 fragment(s) in the ASTPrinter.java or the output while expecting exactly 0 

## Reflection

- [ ] Reflection contains adequate number of code fences
- Found 2 tag(s) in the reflection.md file 

## AST

- [ ] Expr.java file exists (AST generated)
- Did not find the specified file in the interpreter&#x2F;src&#x2F;main&#x2F;java&#x2F;com&#x2F;interpreter&#x2F;lox directory 
- [x] ASTPrinter.java implements RPN without using System.out.println

## Percent complete

Based on the checks achieved, this assignment is `12%` complete.
