### ISSUE TITLE
7 - Control Flow

### ISSUE THREAD

**Issue by dluman** [allegheny-college-cmpsc-201-spring-2024/lox-student#7]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## Tests

- [ ] Break statement ends loop at the correct number (a &#x3D;&#x3D; 7)
- The command returned the error code 1 
- [ ] Ternary expression assesses value of a and returns correct branch
- The command returned the error code 1 

## TODOs

- [ ] Interpreter.java file contains no TODOs
- Found 2 fragment(s) in the Interpreter.java or the output while expecting exactly 0 
- [ ] Parser.java file contains no TODOs
- Found 6 fragment(s) in the Parser.java or the output while expecting exactly 0 
- [ ] Scanner.java file contains no TODOs
- Found 1 fragment(s) in the Scanner.java or the output while expecting exactly 0 
- [ ] TokenType.java file contains no TODOs
- Found 1 fragment(s) in the TokenType.java or the output while expecting exactly 0 
- [ ] test.lox file contains no TODOs
- Found 2 fragment(s) in the test.lox or the output while expecting exactly 0 
- [ ] Reflection contains no TODOs
- Found 6 fragment(s) in the reflection.md or the output while expecting exactly 0 

## Percent complete

Based on the checks achieved, this assignment is `0%` complete.
